### ISSUE TITLE
[BUG] - Error

### ISSUE THREAD

**Issue by brianschardt** [testdeck/testdeck#275] opened 2020-06-28 00:24 UTC
## Testdeck Version

Error 
```
✖ ERROR: --opts: configuring Mocha via 'mocha.opts' is DEPRECATED and no longer supported.
          Please use a configuration file instead.
/Users/brianschardt/Desktop/testdeck-mocha-seed/node_modules/yargs/yargs.js:1172
      else throw err
           ^
```

**Comment by silkentrance** [comment] 2020-07-26 20:32
@brianschardt How about providing us with a PR for this?

**Comment by silkentrance** [comment] 2020-11-19 20:16
@brianschardt I just tested this with the latest version of `testdeck-mocha-seed` and also the latest versions of the dependencies.
However, I am not able to reproduce the above error.

I will remove the mocha.opts and instead provide a working sample .mocharc.yaml, though.

**Comment by silkentrance** [comment] 2020-11-25 12:19
closed by https://github.com/testdeck/testdeck/issues/275

**Closed by silkentrance** 2020-11-25 12:19 UTC
Labels: bug
